$RootDir = Split-Path -Path $CurrentDir -Parent
$TestSitesFolderName = "testsites"
$TestSitesFolder = "$RootDir\$TestSitesFolderName"
$TestProjectName = "V12"
$PackageName = "Dawoe.OEmbedPickerPropertyEditor"
$SolutionName = "Dawoe.OEmbedPickerPropertyEditor"
$SourceDir = "$RootDir\src"
$UmbracoVersion = "12.0.0"
$StarterKitVersion = "11.0.0"